[phases.setup]
nixPkgs = ["nodejs_20"]                  # Yarn no longer needed here

[phases.install]
commands = [
    "corepack enable",
    "corepack install --global yarn@stable",
    "corepack prepare yarn@4.9.1 --activate",
    "yarn install --immutable"
]

[phases.build]
cmds = ["yarn build:backend"]

[deploy]
startCommand = "yarn run start:prod"
restartPolicyMaxRetries = 2

[nixpacks]
packageManager = "yarn"

[environments]
[environments.production]
numReplicas = 1
domain = { enabled = true }
