[build]
builder = "nixpacks"
buildCommand = "npm run build"
watchPatterns = ["**/*.ts", "**/*.js", "**/*.json"]

[deploy]
startCommand = "npm run start:prod"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[environments]
  [environments.production]
    numReplicas = 1
    domain = { enabled = true }