[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm run start:prod"

[environments]
  [environments.production]
    numReplicas = 1
    domain = { enabled = true }
