[phases.setup]
nixPkgs = ["nodejs_20"]
aptPkgs = ["yarn"]


[phases.install]
cmds = [
    "corepack enable",
    "corepack prepare yarn@4.9.1 --activate",
    "yarn install"
]

[build]
builder = "nixpacks"
buildCommand = "yarn run build"

[nixpacks]
packageManager = "yarn"

[deploy]
startCommand = "yarn run start:prod"
restartPolicyMaxRetries = 2

[environments]
  [environments.production]
    numReplicas = 1
    domain = { enabled = true }
