[phases.setup]
nixPkgs = ["nodejs_20"]                  # Yarn no longer needed here
cmds = [
    "corepack enable",
    "corepack prepare yarn@4.9.1 --activate"
]

[phases.install]
cmds = ["yarn install --immutable"]

[phases.build]
cmds = ["yarn build"]

[deploy]
# Call the compiled entrypoint, bypassing Yarn entirely
startCommand = "node dist/main.js"
restartPolicyMaxRetries = 2

[environments]
  [environments.production]
    numReplicas = 1
    domain = { enabled = true }
