#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running tests before push..."
yarn test:integration && yarn test:e2e || (echo "Tests failed. Push aborted." && exit 1)

echo "All tests passed. Proceeding with push..."
